# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0021_singlerecord_signal_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerecord',
            name='delta_time',
            field=models.CharField(default='00-00-00 00:00:00', max_length=250),
        ),
        migrations.AlterField(
            model_name='singlerecord',
            name='compartment',
            field=models.IntegerField(default=0),
        ),
    ]
