# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0023_remove_singlerecord_delta_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='last_seen_pre_defined_max_time',
            field=models.IntegerField(default=240),
        ),
    ]
