# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0026_auto_20170424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerecord',
            name='compartment',
            field=models.CharField(default='CIC', max_length=250),
        ),
    ]
