# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0027_auto_20170424_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartment',
            name='compartment_sensor_num',
            field=models.IntegerField(default=0),
        ),
    ]
