# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0028_compartment_compartment_sensor_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartment',
            name='compartment_sensor_num',
        ),
    ]
