# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0031_auto_20170424_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='soldier_security_class',
            field=models.IntegerField(default=1),
        ),
    ]
