# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0032_soldier_soldier_security_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='current_compartment',
            field=models.CharField(default='CIC', max_length=250),
        ),
    ]
