# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0033_soldier_current_compartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='sleep_time_pre_defined_max_time',
            new_name='lack_of_movement_pre_defined_max_time',
        ),
        migrations.AddField(
            model_name='soldier',
            name='last_time_stamp',
            field=models.CharField(default='2000-01-01 12:34:56', max_length=250),
        ),
    ]
