# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0034_auto_20170429_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='baknaz_team',
            field=models.BooleanField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='soldier',
            name='officer',
            field=models.BooleanField(default=0, max_length=3),
        ),
    ]
