# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0035_auto_20170430_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_mode', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='soldier',
            name='baknaz_team',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='officer',
            field=models.BooleanField(default=0),
        ),
    ]
