# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0018_singlerecord_soldier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='tag',
            new_name='tag_string',
        ),
    ]
