# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0019_auto_20170318_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='tag_string',
            new_name='tag',
        ),
    ]
