# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0020_auto_20170318_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerecord',
            name='signal_strength',
            field=models.CharField(default='0x00', max_length=250),
        ),
    ]
